pipeline:
  create_cluster:
    image: banzaicloud/ci-pipeline-client:0.11
    cluster:
      action: GetCluster
      cloud: google
      name: stoader04wx
    action: EnsureCluster
  test:
    image: maven:3.5-jdk-11-slim
    commands:
    - mvn -Dmaven.repo.local=${PWD}/.m2/repository clean test
  build_image:
    commands:
    - mvn -Dmaven.repo.local=${PWD}/.m2/repository compile jib:build
    environment:
      DOCKER_REPO: '{{ .CICD_REPO }}'
      DOCKER_TAG: '{{ trunc 7 .CICD_COMMIT_SHA }}'
    image: maven:3.5-jdk-11-slim
    secretFrom:
      DOCKER_PASSWORD:
        keyRef: password
        name: docker-hub
      DOCKER_USERNAME:
        keyRef: username
        name: docker-hub
  package_application:
    image: lachlanevenson/k8s-helm:latest
    commands:
    - helm init -c
    - helm repo add banzaicloud-stable https://kubernetes-charts.banzaicloud.com
    - helm dep update ./.banzaicloud/charts/spotguide-spring-boot
    - helm package ./.banzaicloud/charts/spotguide-spring-boot
  install_mysql_user_secret:
    action: InstallSecret
    clusterSecret:
      merge: true
      name: '{{ .CICD_REPO_NAME }}-mysql'
      namespace: default
      sourceSecretName: spring-boot-20191107-gcr-mysql
      spec:
      - name: mysql-username
        source: username
      - name: mysql-password
        source: password
    image: banzaicloud/ci-pipeline-client:0.11
    when:
      branch:
        include:
        - master
  install_mysql_root_secret:
    when:
      branch:
        include:
        - master
    image: banzaicloud/ci-pipeline-client:0.11
    action: InstallSecret
    clusterSecret:
      name: '{{ .CICD_REPO_NAME }}-mysql'
      namespace: default
      merge: true
      spec:
      - name: mysql-root-password
        source: password
  deploy_application:
    action: EnsureDeployment
    deployment:
      name: ./spotguide-spring-boot-1.0.0.tgz
      releaseName: '{{ .CICD_REPO_NAME }}'
      reuseValues: true
      values:
        image:
          pullPolicy: Always
          repository: '{{ .CICD_REPO }}'
          tag: '{{ trunc 7 .CICD_COMMIT_SHA }}'
        ingress:
          annotations:
            kubernetes.io/ingress.class: traefik
            traefik.ingress.kubernetes.io/redirect-permanent: "true"
            traefik.ingress.kubernetes.io/redirect-regex: ^http://(.*)
            traefik.ingress.kubernetes.io/redirect-replacement: https://$1
          enabled: true
          hosts:
          - '{{.CICD_REPO_NAME}}.{{.CLUSTER_NAME}}.{{.ORG_NAME}}.{{.DOMAIN_NAME}}'
        mysql:
          existingSecret: '{{ .CICD_REPO_NAME }}-mysql'
          mysqlDatabase: spring-boot
    image: banzaicloud/ci-pipeline-client:0.11
    when:
      branch:
        include:
        - master
